apiVersion: v2
name: vsftpd
description: A Helm chart for Kubernetes to deploy an FTP server using fauria/vsftpd
version: 0.1.0
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
    - bitnami-common
    version: 2.x.x

