username: "user"
password: "pass"

service:
  type: LoadBalancer

  port: 21
  dataPort: 20
  pasvMinPort: 21100
  pasvMaxPort: 21110
  pasvAddress: "192.168.2.2" # The external IP or domain for PASV mode


image:
  repository: fauria/vsftpd
  tag: latest
  pullPolicy: IfNotPresent

commonLabels: {}

persistence:
  home:
    enabled: true
    size: "1Gi"
    storageClassName: ""
  logs:
    enabled: true
    size: "100Mi"
    storageClassName: ""