apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
 {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.podLabels .Values.commonLabels ) "context" . ) }}
      containers:
        - name: vsftpd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FTP_USER
              value: {{ .Values.username | quote }}
            - name: FTP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.fullname" . }}
                  key: ftp-password
            - name: PASV_ADDRESS
              value: "192.168.2.2" # External IP of your LoadBalancer
            - name: PASV_ENABLE
              value: "YES"
            - name: PASV_MIN_PORT
              value: "21100"
            - name: PASV_MAX_PORT
              value: "21110"
          ports:
            - containerPort: 21
            - containerPort: 20
            - containerPort: 21100
            - containerPort: 21101
            - containerPort: 21102
            - containerPort: 21103
            - containerPort: 21104
            - containerPort: 21105
            - containerPort: 21106
            - containerPort: 21107
            - containerPort: 21108
            - containerPort: 21109
            - containerPort: 21110
          volumeMounts:
            - name: home
              mountPath: "/home/vsftpd"
            - name: logs
              mountPath: "/var/log/vsftpd"
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: {{ include "common.names.fullname" . }}-home-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "common.names.fullname" . }}-logs-pvc
