apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
 {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.podLabels .Values.commonLabels ) "context" . ) }}
      containers:
        - name: vsftpd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FTP_USER
              value: {{ .Values.username | quote }}
            - name: FTP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.fullname" . }}
                  key: ftp-password
            - name: PASV_ADDRESS
              value: "{{ .Values.service.pasvAddress }}"
            - name: PASV_ENABLE
              value: "YES"
            - name: PASV_MIN_PORT
              value: "{{ .Values.service.pasvMinPort }}"
            - name: PASV_MAX_PORT
              value: "{{ .Values.service.pasvMaxPort }}"
          ports:
          - containerPort: {{ .Values.service.port }}
          - containerPort: {{ .Values.service.dataPort }}
          {{- $pasvMinPort := int .Values.service.pasvMinPort }}
          {{- $pasvMaxPort := int .Values.service.pasvMaxPort }}
          {{- $step := 1 }}
          {{- $pasvPorts := untilStep $pasvMinPort $pasvMaxPort $step }}
          {{- range $index, $port := $pasvPorts }}
          - containerPort: {{ $port }}
          {{- end }}

   
          volumeMounts:
            - name: home
              mountPath: "/home/vsftpd"
            - name: logs
              mountPath: "/var/log/vsftpd"
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: {{ include "common.names.fullname" . }}-home-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "common.names.fullname" . }}-logs-pvc
