apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}-home-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.home.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.home.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.logs.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
