apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  ftp-password: {{ .Values.password | b64enc | quote }}

