apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ftp
      port: 21
      targetPort: 21
    - name: ftp-data
      port: 20
      targetPort: 20
    - name: passive-21100
      port: 21100
      targetPort: 21100
    - name: passive-21101
      port: 21101
      targetPort: 21101
    - name: passive-21102
      port: 21102
      targetPort: 21102
    - name: passive-21103
      port: 21103
      targetPort: 21103
    - name: passive-21104
      port: 21104
      targetPort: 21104
    - name: passive-21105
      port: 21105
      targetPort: 21105
    - name: passive-21106
      port: 21106
      targetPort: 21106
    - name: passive-21107
      port: 21107
      targetPort: 21107
    - name: passive-21108
      port: 21108
      targetPort: 21108
    - name: passive-21109
      port: 21109
      targetPort: 21109
    - name: passive-21110
      port: 21110
      targetPort: 21110
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
