apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ftp-command
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: ftp-data
      port: {{ .Values.service.dataPort }}
      targetPort: {{ .Values.service.dataPort }}
    {{- $pasvMinPort := int .Values.service.pasvMinPort }}
    {{- $pasvMaxPort := int .Values.service.pasvMaxPort }}
    {{- $step := 1 }}
    {{- $pasvPorts := untilStep $pasvMinPort $pasvMaxPort $step }}
    {{- range $index, $port := $pasvPorts }}
    - name: pasv-{{ $port }}
      port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}






  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
